"""create initial database tables

Revision ID: 88c22fa01d76
Revises: 
Create Date: 2026-07-27 22:22:01.790000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c22fa01d76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('capacity_rps', sa.Integer(), nullable=False),
    sa.Column('current_load_percent', sa.Float(), nullable=False),
    sa.Column('base_latency_ms', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edge_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edge_nodes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_edge_nodes_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_edge_nodes_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('audience', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('traffic_profile', sa.String(length=40), nullable=False),
    sa.Column('optimization_goal', sa.String(length=40), nullable=False),
    sa.Column('requests_per_second', sa.Integer(), nullable=False),
    sa.Column('payload_size_kb', sa.Integer(), nullable=False),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('warm_cache', sa.Boolean(), nullable=False),
    sa.Column('failover', sa.Boolean(), nullable=False),
    sa.Column('ai_routing', sa.Boolean(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_user_id'), ['user_id'], unique=False)

    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('route_type', sa.String(length=30), nullable=False),
    sa.Column('path', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cache_hit_rate', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_is_selected'), ['is_selected'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('saved_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_results_simulation_id'), ['simulation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_saved_results_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_results_simulation_id'))

    op.drop_table('saved_results')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_routes_is_selected'))

    op.drop_table('routes')
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_user_id'))
        batch_op.drop_index(batch_op.f('ix_simulations_status'))

    op.drop_table('simulations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('edge_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edge_nodes_status'))
        batch_op.drop_index(batch_op.f('ix_edge_nodes_region'))
        batch_op.drop_index(batch_op.f('ix_edge_nodes_code'))

    op.drop_table('edge_nodes')
    # ### end Alembic commands ###
